language: node_js
node_js:
   - 0.6


services:
  - couchdb

before_script:
  - curl -X PUT localhost:5984/myapp_test
  - npm install kanso -g
  - npm install jam -g

script: "kanso install; kanso push http://localhost:5984/myapp_test"

after_script:
  - "kanso push http://travis:Yhu2Dpg5fEezAvdu_j@nwt.iriscouch.com/talk_test --minify"

notifications:
  email:
    recipients:
      - mw@data.io
      - ryan@eckoit.com